import {MONSTERS,AREAS,ITEMS,monsterById,stats,typeMultiplier} from './data.js';
const $=id=>document.getElementById(id), clamp=(n,a,b)=>Math.min(b,Math.max(a,n));
const ids=['emberpup','mossling','aquafluff']; const state={screen:'title',area:0,pos:{x:50,y:78},party:[],caught:[],level:3,xp:0,route:0,battle:null,online:false,ws:null,selfId:null,players:new Map()};
const uid=()=>globalThis.crypto?.randomUUID?.()||('u-'+Date.now()+'-'+Math.random());
function save(){try{localStorage.setItem('monster-veil-save',JSON.stringify({...state,ws:null,players:[]}));return true}catch{return false}}
function load(){try{const x=JSON.parse(localStorage.getItem('monster-veil-save')||'null');if(!x?.party?.length)return false;Object.assign(state,x,{ws:null,players:new Map(),battle:null,online:false});return true}catch{return false}}
function screen(s){['titleScreen','starterScreen','gameScreen','battleScreen'].forEach(id=>$(id).classList.add('hidden'));$(s).classList.remove('hidden');state.screen=s.replace('Screen','')}
function say(t){$('message').textContent=t}
function xpNeed(){return 20+state.level*6}
function route(){return state.route<=-4?'WILD':state.route>=4?'KIND':'BALANCE'}
function partyMon(id,l=3){const m=monsterById(id),hp=stats(m,l).hp;return{uid:uid(),id:id,level:l,hp:hp,maxHp:hp}}
function art(id){const m=monsterById(id);return '<div class="creature" style="--c:'+m.color+'"><span></span></div>'}
function render(){if(state.screen==='game'){const a=AREAS[state.area];$('areaName').textContent=a.name;$('levelLabel').textContent=state.level;$('xpLabel').textContent=state.xp+' / '+xpNeed();$('caughtLabel').textContent=state.caught.length;$('partyCount').textContent=state.party.length+' / 6';$('routeLabel').textContent=route();$('player').style.left=state.pos.x+'%';$('player').style.top=state.pos.y+'%';renderParty();renderOthers()}if(state.battle)renderBattle()}
function renderParty(){const box=$('partyList');box.innerHTML='';state.party.forEach(p=>{const m=monsterById(p.id);const d=document.createElement('div');d.className='party-item';d.innerHTML='<div class="mini-art">'+art(p.id)+'</div><div><b>'+m.name+'</b><div class="muted">Lv.'+p.level+' / '+m.type+'</div><div class="small">HP '+p.hp+'/'+p.maxHp+'</div></div>';box.appendChild(d)})}
function renderOthers(){const box=$('otherPlayers');box.innerHTML='';state.players.forEach(p=>{if(p.id===state.selfId)return;const d=document.createElement('div');d.className='other';d.style.left=p.x+'%';d.style.top=p.y+'%';d.title=p.name;box.appendChild(d)})}
function move(dx,dy){if(state.battle)return;state.pos.x=clamp(state.pos.x+dx,3,97);state.pos.y=clamp(state.pos.y+dy,4,96);render();if(state.online&&state.ws?.readyState===1)state.ws.send(JSON.stringify({type:'move',x:state.pos.x,y:state.pos.y}));if(spotGrass()&&Math.random()<.15)battle(monsterById(AREAS[state.area].encounters[Math.floor(Math.random()*AREAS[state.area].encounters.length)]),false)}
function spotGrass(){const x=state.pos.x,y=state.pos.y;return(x<36&&y<40)||(x>58&&y<34)||(x>20&&x<45&&y>70)}
function battle(mon,isBoss){if(!mon||!state.party[0])return;const l=AREAS[state.area].level+(isBoss?2:Math.floor(Math.random()*3));const hp=stats(mon,l).hp;state.battle={isBoss,enemy:{id:mon.id,level:l,hp,maxHp:hp},hero:state.party[0].uid,bonus:0};screen('battleScreen');$('battleLog').textContent=(isBoss?'門番の':'野生の')+mon.name+'が現れた！';buildMoves();render()}
function hero(){return state.party.find(p=>p.uid===state.battle?.hero)||state.party[0]}
function renderBattle(){const b=state.battle,h=hero(),e=monsterById(b.enemy.id),hm=monsterById(h.id);$('enemyLabel').textContent=b.isBoss?'門番':'野生';$('enemyName').textContent=e.name;$('enemyMeta').textContent='Lv.'+b.enemy.level+' / '+e.type;$('enemyHp').style.width=100*b.enemy.hp/b.enemy.maxHp+'%';$('enemyHpText').textContent=b.enemy.hp+' / '+b.enemy.maxHp;$('enemyMonster').innerHTML=art(e.id);$('heroName').textContent=hm.name;$('heroMeta').textContent='Lv.'+h.level+' / '+hm.type;$('heroHp').style.width=100*h.hp/h.maxHp+'%';$('heroHpText').textContent=h.hp+' / '+h.maxHp;$('heroMonster').innerHTML=art(h.id)}
function buildMoves(){const e=monsterById(state.battle.enemy.id),g=$('moveGrid');g.innerHTML='';e.moves.forEach((n,i)=>{const b=document.createElement('button');b.textContent=n;b.onclick=()=>attack(i);g.appendChild(b)});g.classList.add('hidden')}
function fight(){ $('moveGrid').classList.toggle('hidden') }
function attack(i){const b=state.battle,h=hero(),hm=monsterById(h.id),e=monsterById(b.enemy.id);$('moveGrid').classList.add('hidden');const types=['ほのお','くさ','みず','でんき','いわ','ひこう','かげ','せいれい'];const mult=typeMultiplier(types[(i+hm.base.atk)%types.length],e.type);const d=Math.max(1,Math.round((8+Math.floor(hm.base.atk/5)+h.level+i*2)*mult));b.enemy.hp=Math.max(0,b.enemy.hp-d);state.route--;addXp(d>=18?6:3);$('battleLog').textContent=hm.moves[i]+'！ '+d+'ダメージ。'+(mult>1?' 効果ばつぐん！':mult<1?' あまり効いていない。':'');renderBattle();if(b.enemy.hp<=0){finish('win');return}enemy()}
function enemy(){const b=state.battle,h=hero(),e=monsterById(b.enemy.id),hm=monsterById(h.id);const d=Math.max(1,6+b.enemy.level+Math.floor(e.base.atk/4)-Math.floor(hm.base.def/6));h.hp=Math.max(1,h.hp-d);$('battleLog').textContent+=' '+e.name+'の反撃！ '+d+'ダメージ。';renderBattle();if(h.hp<=1)setTimeout(()=>finish('lose'),160)}
function talk(){const b=state.battle;if(!b)return;b.bonus+=16;state.route+=2;$('battleLog').textContent=b.isBoss?'門番は静かにこちらを見る。':'少し警戒が解けた。つかまえやすくなった！';renderBattle()}
function catchIt(){const b=state.battle;if(!b||b.isBoss)return;const c=Math.min(.92,.22+(b.enemy.maxHp-b.enemy.hp)/b.enemy.maxHp*.68+b.bonus/100);if(Math.random()<c){state.caught.push(b.enemy.id);if(state.party.length<6)state.party.push({uid:uid(),id:b.enemy.id,level:b.enemy.level,hp:b.enemy.hp,maxHp:b.enemy.maxHp});state.route++;finish('caught')}else{b.bonus=0;$('battleLog').textContent='つかまえ球が弾かれた！';enemy()}}
function item(){const h=hero();h.hp=Math.min(h.maxHp,h.hp+ITEMS.berry.heal);state.route++;$('battleLog').textContent=ITEMS.berry.name+'でHPが'+ITEMS.berry.heal+'回復した。';renderBattle();enemy()}
function run(){const b=state.battle;if(!b)return;if(b.isBoss){$('battleLog').textContent='門番は道を譲らない。';enemy();return}state.route++;finish('run')}
function addXp(n){state.xp+=n;while(state.xp>=xpNeed()){state.xp-=xpNeed();state.level++;state.party.forEach(p=>{p.level=Math.min(20,p.level+1);const hp=stats(monsterById(p.id),p.level).hp;p.maxHp=hp;p.hp=hp});say('レベルアップ！ 旅レベルが '+state.level+' になった。')}}
function finish(r){const b=state.battle,name=monsterById(b.enemy.id).name;if(r==='win'){addXp(12);if(b.isBoss)advance();else say('勝利！ '+name+'は去っていった。')}else if(r==='caught'){say(name+'が仲間になった！')}else if(r==='lose'){hero().hp=hero().maxHp;say('相棒が元気を取り戻した。')}else say('無事に立ち去った。');state.battle=null;screen('gameScreen');save();render()}
function advance(){if(state.area<AREAS.length-1){state.area++;state.pos={x:50,y:80};say(AREAS[state.area].name+'へ進めるようになった！')}else say('星境の最奥に到着！ 冒険はひと区切り。')}
function gate(){battle(monsterById(AREAS[state.area].boss),true)}
function bag(){let html='<h2>どうぐ・図鑑</h2><p class="muted">発見数 '+state.caught.length+' </p><div class="dex-grid">';MONSTERS.forEach(m=>{const seen=state.caught.includes(m.id);html+='<div class="dex-card"><div class="mini-art">'+art(m.id)+'</div><div><b>'+(seen?m.name:'？？？？')+'</b><div class="muted">'+(seen?m.type:'未発見')+'</div></div></div>'});html+='</div>';$('modalBody').innerHTML=html;$('modal').classList.remove('hidden')}
function starters(){const box=$('starterList');box.innerHTML='';ids.forEach(id=>{const m=monsterById(id),b=document.createElement('button');b.className='starter';b.innerHTML='<div class="starter-art">'+art(id)+'</div><div class="starter-name">'+m.name+'</div><span class="type-pill">'+m.type+'</span><p class="muted">'+m.moves.join(' / ')+'</p>';b.onclick=()=>{state.area=0;state.pos={x:50,y:78};state.party=[partyMon(id)];state.caught=[id];state.level=3;state.xp=0;state.route=0;screen('gameScreen');say('旅の始まり。草むらへ行ってみよう。');save();render()};box.appendChild(b)})}
function online(){if(state.online){state.ws?.close();return}try{const ws=new WebSocket((location.protocol==='https:'?'wss':'ws')+'://'+location.host);state.ws=ws;$('onlineStatus').textContent='接続中…';ws.onopen=()=>{state.online=true;$('onlineBtn').textContent='切断';ws.send(JSON.stringify({type:'join',name:'旅人'}))};ws.onmessage=e=>{let m;try{m=JSON.parse(e.data)}catch{return}if(m.type==='joined'){state.selfId=m.selfId;state.players=new Map(m.room.players.map(p=>[p.id,p]));$('roomInfo').textContent='ルーム '+m.room.id+' / '+m.room.players.length+'人';chat('システム：接続しました')}if(m.type==='player_joined'){state.players.set(m.player.id,m.player);renderOthers()}if(m.type==='player_moved'){const p=state.players.get(m.player.id);if(p){p.x=m.player.x;p.y=m.player.y;renderOthers()}}if(m.type==='player_left'){state.players.delete(m.playerId);renderOthers()}if(m.type==='chat')chat(m.name+'：'+m.text)};ws.onclose=()=>{state.online=false;state.ws=null;state.players.clear();$('onlineStatus').textContent='オフライン';$('onlineBtn').textContent='つながる';$('roomInfo').textContent='';renderOthers()};ws.onerror=()=>{$('onlineStatus').textContent='接続に失敗'}}catch{$('onlineStatus').textContent='オンラインを利用できません'}}
function chat(t){const d=document.createElement('div');d.textContent=t;$('chatLog').appendChild(d);$('chatLog').scrollTop=$('chatLog').scrollHeight}
function sendChat(){const t=$('chatInput').value.trim();if(t&&state.ws?.readyState===1){state.ws.send(JSON.stringify({type:'chat',text:t}));$('chatInput').value=''}}
$('newGameBtn').onclick=()=>screen('starterScreen');$('loadGameBtn').onclick=()=>{if(load()){screen('gameScreen');say('セーブデータを読み込みました。');render()}else screen('starterScreen')};$('saveBtn').onclick=()=>{save();say('セーブしました。')};$('bagBtn').onclick=bag;$('onlineBtn').onclick=online;$('chatSend').onclick=sendChat;$('chatInput').addEventListener('keydown',e=>{if(e.key==='Enter')sendChat()});$('modalClose').onclick=()=>$('modal').classList.add('hidden');
document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>{const d=b.dataset.move;move(d==='left'?-4:d==='right'?4:0,d==='up'?-4:d==='down'?4:0)});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>({fight,talk,catch:catchIt,item,run}[b.dataset.action])());document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA'].includes(e.target.tagName))return;const k=e.key.toLowerCase();if(state.screen==='game'){if(k==='w'||e.key==='ArrowUp')move(0,-4);else if(k==='s'||e.key==='ArrowDown')move(0,4);else if(k==='a'||e.key==='ArrowLeft')move(-4,0);else if(k==='d'||e.key==='ArrowRight')move(4,0);else if(k==='g')gate();else if(k==='b')bag()}else if(state.screen==='battle'){if(k==='f')fight();else if(k==='t')talk();else if(k==='c')catchIt();else if(k==='i')item();else if(k==='r')run()}});starters();