const $=id=>document.getElementById(id),API="/api",SAVE="pokemon-star-v2",VERSION=7;
const STARTERS=["bulbasaur","charmander","squirtle"],ENCOUNTERS=["pidgey","rattata","caterpie","pikachu"];
const NAMES={bulbasaur:"フシギダネ",charmander:"ヒトカゲ",squirtle:"ゼニガメ",pidgey:"ポッポ",rattata:"コラッタ",caterpie:"キャタピー",pikachu:"ピカチュウ",oddish:"ナゾノクサ"};
const state={screen:"title",area:"town",x:10,y:11,dir:"down",party:[],money:3000,badges:0,dex:new Set(),items:{potion:5,pokeball:10},battle:null,event:null};
const cache=new Map(),imgCache=new Map();let raf=0,lastStep=0,frame=0;
const TILE=32,COLS=20,ROWS=15;
const MAPS={
 town:{name:"星見町",tiles:[
"####################","#tttttttttttttttttt#","#ttttt....ttttttttt#","#ttttt....ttttttttt#","#tt..gggggg..ttttt#","#tt..gggggg..tttttt#","#....gggggg.........#","#....gg..gg.........#","#....gg..gg.........#","#....gggggg.........#","#...................#","#......~~~~.........#","#......~~~~.........#","#...................#","####################"]},
 route:{name:"1番道路",tiles:[
"####################","#..gggg....gggg....#","#..gggg....gggg....#","#..gggg....gggg....#","#..gggg....gggg....#","#..................#","#..gggg....gggg....#","#..gggg....gggg....#","#..................#","#..gggggggggggggg..#","#..gggggggggggggg..#","#..................#","#..................#","#..................#","####################"]},
 lake:{name:"ミズホ湿原",tiles:[
"####################","#gggggggg~~~~ggggg#","#gggggg~~~~~~ggggg#","#gggg~~~~~~~~~~ggg#","#gggg~~~~~~~~~~ggg#","#gggggg~~~~~~ggggg#","#gggggggg~~~~ggggg#","#..................#","#..gggggg....gggg..#","#..gggggg....gggg..#","#..................#","#..................#","#..................#","#..................#","####################"]}};
function tileAt(x,y){const m=MAPS[state.area]||MAPS.town;return m.tiles[y]?.[x]||"#"}function solid(t){return "#t~".includes(t)}
function walkable(x,y){const t=tileAt(x,y);return !solid(t)}
function stepDir(dx,dy){if(state.screen!=="world"||state.event)return;state.dir=dy<0?"up":dy>0?"down":dx<0?"left":"right";const nx=state.x+dx,ny=state.y+dy;if(!walkable(nx,ny)){say("そこには進めない。");return}state.x=nx;state.y=ny;state.frame=(state.frame||0)+1;renderWorld();if(state.area==="route"&&tileAt(nx,ny)==="g"&&Math.random()<.16)setTimeout(()=>wildEncounter(),80)}
function show(id){document.querySelectorAll(".screen").forEach(x=>x.classList.add("hidden"));$(id).classList.remove("hidden");state.screen=id==="world"?"world":id}
function say(t){$("mapText").textContent=t}
function jp(name,fallback){return NAMES[name]||fallback||name}
async function pokemon(name){if(cache.has(name))return cache.get(name);const r=await fetch(API+"/pokemon/"+name);if(!r.ok)throw Error("pokemon");const p=await r.json();cache.set(name,p);return p}
async function moveData(name){const k="m:"+name;if(cache.has(k))return cache.get(k);const r=await fetch(API+"/move/"+name);if(!r.ok)throw Error("move");const m=await r.json();cache.set(k,m);return m}
function sprite(p,back=false){return p.sprite||"/api/sprite/"+p.id+(back?"?back=1":"")}
function stats(p,l){const b=Object.fromEntries(p.stats.map(x=>[x.stat.name,x.base_stat]));return{hp:Math.floor((2*b.hp*l)/100)+l+10,attack:Math.floor((2*b.attack*l)/100)+5,defense:Math.floor((2*b.defense*l)/100)+5,spAttack:Math.floor((2*b["special-attack"]*l)/100)+5,spDefense:Math.floor((2*b["special-defense"]*l)/100)+5,speed:Math.floor((2*b.speed*l)/100)+5}}
async function makeMon(name,lvl){const p=await pokemon(name);const st=stats(p,lvl);const levelMoves=p.moves.filter(x=>x.level<=lvl).sort((a,b)=>b.level-a.level).slice(0,4);const moves=[];for(const q of levelMoves){try{const m=await moveData(q.name);moves.push({name:m.name,nameJa:m.nameJa,type:m.type,power:m.power,accuracy:m.accuracy,pp:m.pp,maxPp:m.pp,damageClass:m.damageClass})}catch{}}if(!moves.length)moves.push({name:"tackle",nameJa:"たいあたり",type:"normal",power:40,accuracy:100,pp:35,maxPp:35,damageClass:"physical"});return{species:p.name,nameJa:p.nameJa||jp(name),level:lvl,stats:st,currentHp:st.hp,moves,sprite:sprite(p)}}
async function starterList(){const box=$("starterList");box.innerHTML="";for(const n of STARTERS){const p=await pokemon(n);const b=document.createElement("button");b.className="starter-card";b.innerHTML='<img src="'+sprite(p)+'"><b>'+jp(n,p.nameJa)+'</b><span>'+p.types.join(" / ")+"</span>";b.onclick=()=>newGame(n);box.appendChild(b)}}
async function newGame(starter){state.area="town";state.x=10;state.y=11;state.money=3000;state.badges=0;state.items={potion:5,pokeball:10};state.dex=new Set();state.party=[await makeMon(starter,5)];state.dex.add(starter);save();show("world");renderWorld();say(jp(starter)+"といっしょに旅に出よう！")}
function save(){localStorage.setItem(SAVE,JSON.stringify({version:VERSION,area:state.area,x:state.x,y:state.y,dir:state.dir,party:state.party,money:state.money,badges:state.badges,items:state.items,dex:[...state.dex]}));say("セーブした。")}
async function load(){const s=JSON.parse(localStorage.getItem(SAVE)||"null");if(!s||s.version!==VERSION)return false;Object.assign(state,s);state.dex=new Set(s.dex||[]);show("world");renderWorld();say("つづきから再開した。");return true}
function px(ctx,x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(x,y,w,h)}
function grass(ctx,x,y,f){const sway=[0,1,0,-1,0,1][f%6];for(let i=0;i<7;i++){const xx=x+4+(i*5)%24;px(ctx,xx+sway,y+18-(i%3)*2,2,8,"#3f8b4e");px(ctx,xx+2+sway,y+14-(i%4),1,6,"#77b85c")}}
function tile(ctx,t,x,y,f){if(t==="#"){px(ctx,x,y,32,32,"#35633d");px(ctx,x+3,y+3,26,26,"#2d5737");px(ctx,x+8,y+6,3,4,"#477a48");return}if(t==="."){px(ctx,x,y,32,32,"#c9b27c");px(ctx,x,y+28,32,4,"#b19a67");px(ctx,x+6+(f%3),y+8,2,2,"#e1d29b");px(ctx,x+22-(f%2),y+18,2,2,"#a68d5d")}if(t==="g"){px(ctx,x,y,32,32,"#73b45c");px(ctx,x+2,y+2,28,28,"#6cac57");grass(ctx,x,y,f)}if(t==="~"){px(ctx,x,y,32,32,"#62b4c6");px(ctx,x+3,y+8+(f%4),25,2,"#91d4da");px(ctx,x+9,y+19-((f+2)%4),18,2,"#4a9fb5")}if(t==="t"){px(ctx,x,y,32,32,"#5c9e50");px(ctx,x+4,y+4,24,22,"#2f703e");px(ctx,x+8,y+2,16,7,"#3c8045");px(ctx,x+12,y+24,8,8,"#7a5434")}}
function drawHouse(ctx,x,y){px(ctx,x,y,96,64,"#8b573c");px(ctx,x+4,y+4,88,40,"#d66a4b");ctx.fillStyle="#8b3e35";ctx.beginPath();ctx.moveTo(x-8,y+10);ctx.lineTo(x+48,y-26);ctx.lineTo(x+104,y+10);ctx.fill();px(ctx,x+38,y+38,20,26,"#563d31");px(ctx,x+10,y+22,18,13,"#b9e0df");px(ctx,x+68,y+22,18,13,"#b9e0df")}
function drawPlayer(ctx,x,y,f){const bob=f%2?1:0;px(ctx,x+7,y+23+bob,18,5,"#33453d");px(ctx,x+10,y+4+bob,12,12,"#f0c2a3");px(ctx,x+8,y+1+bob,16,6,"#315d9b");px(ctx,x+8,y+16+bob,16,15,"#f4f4ef");px(ctx,x+9,y+29+bob,6,7,"#3b65a0");px(ctx,x+17,y+29+bob,6,7,"#3b65a0")}
function drawNpc(ctx,x,y,f){const bob=f%2;px(ctx,x+7,y+24+bob,18,5,"#333");px(ctx,x+10,y+4+bob,12,12,"#eac0a5");px(ctx,x+8,y+1+bob,16,5,"#eee");px(ctx,x+8,y+16+bob,16,14,"#fff");px(ctx,x+4,y+14+bob,5,10,"#6d8090");}
function renderWorld(){const c=$("map"),ctx=c.getContext("2d");ctx.clearRect(0,0,c.width,c.height);const f=frame%6,m=MAPS[state.area];for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++)tile(ctx,tileAt(x,y),x*TILE,y*TILE,f);if(state.area==="town"){drawHouse(ctx,32,42);drawHouse(ctx,480,42);drawNpc(ctx,13*TILE,5*TILE,f);drawNpc(ctx,4*TILE,9*TILE,f)}if(state.area==="lake"){drawNpc(ctx,13*TILE,7*TILE,f)}drawPlayer(ctx,state.x*TILE,state.y*TILE,f);$("place").textContent=m.name;$("money").textContent=state.money+"円";$("badges").textContent="バッジ "+state.badges;renderParty()}
function renderParty(){const b=$("party");b.innerHTML=state.party.map(p=>'<div class="party-mini"><img src="'+p.sprite+'"><span>'+p.nameJa+' Lv.'+p.level+'<br>HP '+p.currentHp+'/'+p.stats.hp+'</span></div>').join("")}
function anim(){frame++;if(state.screen==="world")renderWorld();if(state.screen==="battle")drawBattle();raf=requestAnimationFrame(anim)}
function introDraw(){const c=$("scene"),ctx=c.getContext("2d"),f=frame%6;ctx.fillStyle="#8dcbd5";ctx.fillRect(0,0,640,170);ctx.fillStyle="#74aa5d";ctx.fillRect(0,170,640,190);ctx.fillStyle="#62aebd";ctx.fillRect(340,85,240,150);for(let i=0;i<35;i++){px(ctx,(i*83)%640,180+(i*37)%160,2,7,"#43894b")}px(ctx,440,42,48,75,"#e7edf0");px(ctx,452,28,24,18,"#eee");px(ctx,457,53,14,8,"#eac1a5");px(ctx,454,76,20,40,"#fff");drawPlayer(ctx,175,215,f);const p=imgCache.get("psyduck");if(p?.complete)ctx.drawImage(p,250,105,80,80);const l=imgCache.get("lotad");if(l?.complete)ctx.drawImage(l,470,135,70,70)}
const LINES=[["？？？","……ここは、ポケモンたちが集まる池。"],["アサギ博士","待ってくれ！ 君に話があるんだ。"],["アサギ博士","私はポケモンの暮らしを研究している。"],["アサギ博士","この地方では、まだ知られていないポケモンの生態がある。"],["アサギ博士","研究所に3匹のポケモンを用意してある。"],["アサギ博士","さあ、君の相棒を選んでくれ。"]];
let line=0,char=0,lastType=0;
function cutsceneStart(){show("cutscene");line=0;char=0;lastType=performance.now();for(const n of ["psyduck","lotad"])pokemon(n).then(p=>{const im=new Image();im.src=sprite(p);imgCache.set(n,im)})}
function cutsceneLoop(){introDraw();const now=performance.now();const target=LINES[line][1];if(char<target.length&&now-lastType>55){char++;lastType=now}$("speaker").textContent=LINES[line][0];$("text").textContent=target.slice(0,char);requestAnimationFrame(cutsceneLoop)}
function advance(){const target=LINES[line][1];if(char<target.length){char=target.length;return}if(line<LINES.length-1){line++;char=0;lastType=performance.now();return}show("starter");starterList()}
async function wildEncounter(){if(state.screen!=="world"||state.battle)return;const name=ENCOUNTERS[Math.floor(Math.random()*ENCOUNTERS.length)];const enemy=await makeMon(name,4+state.badges*3);state.dex.add(name);state.battle={enemy,turn:"player"};show("battle");setBattle("野生の"+enemy.nameJa+"が現れた！")}
function setBattle(t){$("battleMessage").textContent=t;renderBattleUI()}
function renderBattleUI(){const b=state.battle;if(!b)return;const p=state.party[0],e=b.enemy;$("enemyName").textContent=e.nameJa;$("enemyLevel").textContent="Lv."+e.level;$("playerName").textContent=p.nameJa;$("playerLevel").textContent="Lv."+p.level;$("enemyHP").style.width=Math.max(0,e.currentHp/e.stats.hp*100)+"%";$("playerHP").style.width=Math.max(0,p.currentHp/p.stats.hp*100)+"%"}
function drawBattle(){const c=$("battleCanvas"),ctx=c.getContext("2d");ctx.clearRect(0,0,960,540);const f=frame%6;ctx.fillStyle="#a8d1dd";ctx.fillRect(0,0,960,290);ctx.fillStyle="#80b765";ctx.fillRect(0,290,960,250);ctx.fillStyle="#6c9957";ctx.beginPath();ctx.ellipse(730,285,190,50,0,0,7);ctx.fill();ctx.beginPath();ctx.ellipse(260,470,260,65,0,0,7);ctx.fill();const e=state.battle?.enemy,p=state.party[0];if(e)drawSprite(ctx,e.sprite,650,145,220,220,f);if(p)drawSprite(ctx,p.sprite,100,290,260,260,f)}
function drawSprite(ctx,src,x,y,w,h,f){let im=imgCache.get(src);if(!im){im=new Image();im.src=src;imgCache.set(src,im)}if(im.complete)ctx.drawImage(im,x,y+(f%2),w,h)}
async function attack(move){const b=state.battle;if(!b)return;const p=state.party[0],e=b.enemy;const power=move.power||40;const type=move.type||"normal";const mult=e.types.includes(type)?1.2:1;const dmg=Math.max(1,Math.floor((((2*p.level/5+2)*power*(p.stats.attack/p.stats.defense))/50+2)*mult));e.currentHp=Math.max(0,e.currentHp-dmg);setBattle(p.nameJa+"の"+move.nameJa+"！ "+dmg+"のダメージ！");if(e.currentHp<=0){setTimeout(()=>{state.battle=null;show("world");say("野生の"+e.nameJa+"を倒した！");},900);return}setTimeout(()=>enemyTurn(),700)}
async function enemyTurn(){const b=state.battle;if(!b)return;const p=state.party[0],e=b.enemy,m=e.moves[0],d=Math.max(1,Math.floor((2*e.level/5+2)*(m.power||40)*e.stats.attack/e.stats.defense/10));p.currentHp=Math.max(0,p.currentHp-d);setBattle("野生の"+e.nameJa+"の"+m.nameJa+"！");if(p.currentHp<=0)setTimeout(()=>{p.currentHp=p.stats.hp;state.battle=null;show("world");say("ポケモンセンターへ戻った。")},900)}
function showMoves(){const box=$("moves");box.classList.remove("hidden");$("battleCommands").classList.add("hidden");box.innerHTML=state.party[0].moves.map((m,i)=>'<button data-move="'+i+'">'+m.nameJa+'<br><small>'+m.type+" PP "+m.pp+"/"+m.maxPp+"</small></button>").join("");box.querySelectorAll("[data-move]").forEach(b=>b.onclick=()=>{const m=state.party[0].moves[+b.dataset.move];box.classList.add("hidden");$("battleCommands").classList.remove("hidden");attack(m)})}
function menuOpen(){ $("menuPanel").classList.remove("hidden");$("menuInfo").textContent="図鑑 "+state.dex.size+"匹 / バッジ "+state.badges}
document.addEventListener("keydown",e=>{const k=e.key.toLowerCase();if(state.screen==="world"){if(k==="arrowup"||k==="w")stepDir(0,-1);else if(k==="arrowdown"||k==="s")stepDir(0,1);else if(k==="arrowleft"||k==="a")stepDir(-1,0);else if(k==="arrowright"||k==="d")stepDir(1,0);else if(k==="e"||k==="enter")say("周囲を調べた。");else if(k==="escape")menuOpen()}else if(state.screen==="cutscene"&&(k==="enter"||k==="a"||e.key===" ")){advance()}else if(state.screen==="battle"&&e.key==="Escape"){show("world");state.battle=null}});
$("start").onclick=cutsceneStart;$("sceneNext").onclick=advance;$("sceneSkip").onclick=()=>{show("starter");starterList()};$("continue").onclick=()=>load().then(ok=>{if(!ok)cutsceneStart()});$("save").onclick=save;$("menu").onclick=menuOpen;$("closeMenu").onclick=()=>$("menuPanel").classList.add("hidden");$("closeMenu2").onclick=()=>$("menuPanel").classList.add("hidden");$("heal").onclick=()=>{state.party.forEach(p=>p.currentHp=p.stats.hp);$("menuPanel").classList.add("hidden");say("ポケモンの体力が回復した！")};$("dex").onclick=()=>{$("menuInfo").textContent=[...state.dex].map(n=>jp(n)).join("、")||"まだ登録されていない。"};document.querySelectorAll("[data-cmd]").forEach(b=>b.onclick=()=>{const c=b.dataset.cmd;if(c==="fight")showMoves();else if(c==="run"){state.battle=null;show("world");say("うまく逃げ切れた！")}else if(c==="bag"){$("bag").classList.remove("hidden");$("battleCommands").classList.add("hidden")}else if(c==="pokemon"){const alive=state.party.findIndex(p=>p.currentHp>0);if(alive>0){state.party.unshift(state.party.splice(alive,1)[0]);renderBattleUI();setBattle("ポケモンを入れ替えた！")}}});$("bag").querySelector('[data-item="back"]').onclick=()=>{$("bag").classList.add("hidden");$("battleCommands").classList.remove("hidden")};$("bag").querySelector('[data-item="potion"]').onclick=()=>{const p=state.party[0];p.currentHp=Math.min(p.stats.hp,p.currentHp+20);setBattle("キズぐすりを使った！");$("bag").classList.add("hidden");$("battleCommands").classList.remove("hidden");setTimeout(enemyTurn,600)};$("bag").querySelector('[data-item="pokeball"]').onclick=()=>{if(state.battle?.enemy&&state.items.pokeball>0){state.items.pokeball--;state.party.push(state.battle.enemy);state.battle=null;show("world");say("野生のポケモンをつかまえた！")}};window.addEventListener("load",()=>{starterList();raf=requestAnimationFrame(anim);cutsceneLoop()});